# Generated by Django 4.0.5 on 2022-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
