# Generated by Django 4.0.5 on 2022-07-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_No',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_Name',
        ),
    ]
