# Generated by Django 4.0.6 on 2022-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_credit_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
