# Generated by Django 4.0.5 on 2022-07-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_companies', '0003_alter_country_flag'),
        ('customers', '0003_alter_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_Card_No',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_companies.flight')),
            ],
        ),
    ]
