# Generated by Django 4.0.5 on 2022-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_credit_card_no_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
